# This is a basic workflow to help you get started with Actions

name: Build Staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['staging']
  pull_request:
    branches: ['staging']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: Install yarn dependencies
        run: yarn install
      # - name: Yarn Test
      # run: yarn test
      - name: Build project assets
        run: yarn build
# deploy:
#   needs: build
#   runs-on: ubuntu-latest
#   steps:
#     - name: Deploy code
#       uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: '16.16.0'
#     - name: Install yarn dependencies
#       run: yarn install
#     - name: Install doctl
#       uses: digitalocean/action-doctl@v2
#       with:
#         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#     - name: Save DigitalOcean kubeconfig
#       run: doctl kubernetes cluster kubeconfig save testing-cluster
